// src/constants/semiarido.js
/**
 * Lista oficial dos 278 municípios da Bahia pertencentes à delimitação do Semiárido (SUDENE / Governo da Bahia).
 * Total de municípios no estado: 417.
 * Cobertura territorial do Semiárido: ~66.7% dos municípios.
 */

export const SEMIARIDO_TOTAL_MUNICIPIOS = 278;
export const BAHIA_TOTAL_MUNICIPIOS = 417;

export const SEMIARIDO_MUNICIPIOS = [
  "Capim Grosso",
  "Pintadas",
  "São José do Jacuípe",
  "Nova Fátima",
  "Quixabeira",
  "Várzea do Poço",
  "Baixa Grande",
  "Mairi",
  "Ipirá",
  "Várzea da Roça",
  "Pé de Serra",
  "Gavião",
  "Capela do Alto Alegre",
  "Riachão do Jacuípe",
  "Serra Preta",
  "Ibipitanga",
  "Botuporã",
  "Caturama",
  "Érico Cardoso",
  "Paramirim",
  "Rio do Pires",
  "Macaúbas",
  "Boquira",
  "Santa Maria da Vitória",
  "São Félix do Coribe",
  "Cocos",
  "Santana",
  "Coribe",
  "Tabocas do Brejo Velho",
  "Canápolis",
  "Serra Dourada",
  "Brejolândia",
  "Barreiras",
  "Formosa do Rio Preto",
  "Angical",
  "Wanderley",
  "Riachão das Neves",
  "Cristópolis",
  "Mansidão",
  "Santa Rita de Cássia",
  "Cotegipe",
  "Baianópolis",
  "Buritirama",
  "Ibicoara",
  "Mucugê",
  "Jussiape",
  "Marcionílio Souza",
  "Rio de Contas",
  "Piatã",
  "Lençóis",
  "Seabra",
  "Abaíra",
  "Andaraí",
  "Novo Horizonte",
  "Barra da Estiva",
  "Morro do Chapéu",
  "Bonito",
  "Iraquara",
  "Boninal",
  "Ibitiara",
  "Utinga",
  "Itaeté",
  "Souto Soares",
  "Palmeiras",
  "Wagner",
  "Nova Redenção",
  "Iramaia",
  "Irecê",
  "Gentio do Ouro",
  "Lapão",
  "América Dourada",
  "Cafarnaum",
  "João Dourado",
  "Canarana",
  "Uibaí",
  "Barra do Mendes",
  "Central",
  "Mulungu do Morro",
  "Presidente Dutra",
  "Ibipeba",
  "Xique-Xique",
  "Itaguaçu da Bahia",
  "Ipupiara",
  "Ibititá",
  "São Gabriel",
  "Jussara",
  "Barro Alto",
  "Paulo Afonso",
  "Abaré",
  "Macururé",
  "Chorrochó",
  "Rodelas",
  "Glória",
  "Crisópolis",
  "Olindina",
  "Itapicuru",
  "Sátiro Dias",
  "Inhambupe",
  "Jequié",
  "Boa Nova",
  "Manoel Vitorino",
  "Itagi",
  "Itapetinga",
  "Caatiba",
  "Nova Canaã",
  "Maiquinique",
  "Itororó",
  "Potiraguá",
  "Itarantim",
  "Macarani",
  "Itambé",
  "Iguaí",
  "Jacobina",
  "Serrolândia",
  "Umburanas",
  "Várzea Nova",
  "Miguel Calmon",
  "Caém",
  "Ourolândia",
  "Mirangaba",
  "Saúde",
  "Itatim",
  "Itaberaba",
  "Iaçu",
  "Mundo Novo",
  "Tapiramutá",
  "Santa Terezinha",
  "Ruy Barbosa",
  "Macajuba",
  "Ibiquera",
  "Boa Vista do Tupim",
  "Piritiba",
  "Rafael Jambeiro",
  "Lajedinho",
  "Andorinha",
  "Jaguarari",
  "Senhor do Bonfim",
  "Antônio Gonçalves",
  "Pindobaçu",
  "Campo Formoso",
  "Filadélfia",
  "Ponto Novo",
  "Caldeirão Grande",
  "Feira de Santana",
  "Anguera",
  "Santo Estêvão",
  "Ipecaetá",
  "Tanquinho",
  "Água Fria",
  "Santanópolis",
  "Antônio Cardoso",
  "Santa Bárbara",
  "Castro Alves",
  "Cabaceiras do Paraguaçu",
  "Ribeira do Pombal",
  "Cícero Dantas",
  "Ribeira do Amparo",
  "Heliópolis",
  "Novo Triunfo",
  "Adustina",
  "Coronel João Sá",
  "Paripiranga",
  "Euclides da Cunha",
  "Banzaê",
  "Jeremoabo",
  "Fátima",
  "Cipó",
  "Sítio do Quinto",
  "Nova Soure",
  "Pedro Alexandre",
  "Santa Brígida",
  "Antas",
  "Juazeiro",
  "Sobradinho",
  "Canudos",
  "Curaçá",
  "Uauá",
  "Sento Sé",
  "Remanso",
  "Casa Nova",
  "Campo Alegre de Lourdes",
  "Pilão Arcado",
  "Brumado",
  "Caculé",
  "Malhada de Pedras",
  "Guanambi",
  "Caetité",
  "Urandi",
  "Dom Basílio",
  "Ibiassucê",
  "Livramento de Nossa Senhora",
  "Candiba",
  "Tanhaçu",
  "Tanque Novo",
  "Iuiu",
  "Sebastião Laranjeiras",
  "Ituaçu",
  "Rio do Antônio",
  "Pindaí",
  "Palmas de Monte Alto",
  "Contendas do Sincorá",
  "Lagoa Real",
  "Valente",
  "Barrocas",
  "Ichu",
  "Retirolândia",
  "Teofilândia",
  "Serrinha",
  "São Domingos",
  "Santaluz",
  "Conceição do Coité",
  "Itiúba",
  "Araci",
  "Lamarão",
  "Tucano",
  "Quijingue",
  "Candeal",
  "Monte Santo",
  "Biritinga",
  "Queimadas",
  "Cansanção",
  "Nordestina",
  "Vitória da Conquista",
  "Licínio de Almeida",
  "Mortugaba",
  "Piripá",
  "Aracatu",
  "Presidente Jânio Quadros",
  "Condeúba",
  "Caetanos",
  "Cordeiros",
  "Caraíbas",
  "Maetinga",
  "Barra do Choça",
  "Tremedal",
  "Anagé",
  "Poções",
  "Guajeru",
  "Planalto",
  "Jacaraci",
  "Bom Jesus da Serra",
  "Mirante",
  "Encruzilhada",
  "Cândido Sales",
  "Ribeirão do Largo",
  "Belo Campo",
  "Amargosa",
  "Lafaiete Coutinho",
  "Ubaíra",
  "Maracás",
  "Nova Itarana",
  "Santa Inês",
  "Elísio Medrado",
  "Planaltino",
  "Jaguaquara",
  "Milagres",
  "Itiruçu",
  "Brejões",
  "Lajedo do Tabocal",
  "Cravolândia",
  "Irajuba",
  "Itaquara",
  "Bom Jesus da Lapa",
  "Ibotirama",
  "Matina",
  "Riacho de Santana",
  "Oliveira dos Brejinhos",
  "Igaporã",
  "Feira da Mata",
  "Brotas de Macaúbas",
  "Muquém do São Francisco",
  "Serra do Ramalho",
  "Morpará",
  "Carinhanha",
  "Malhada",
  "Barra",
  "Sítio do Mato",
  "Paratinga"
];

export function normalizeMunicipioName(value) {
  if (!value) return '';
  return String(value)
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

// Set pré-computado para busca O(1)
export const SEMIARIDO_MUNICIPIOS_NORMALIZADOS = new Set(
  SEMIARIDO_MUNICIPIOS.map(normalizeMunicipioName)
);

// Dicionário de correções e sinônimos conhecidos
const CORRECOES_SEMIARIDO = {
  'dias davila': 'dias d avila',
  'santa teresinha': 'santa terezinha',
  'camaca': 'camacan',
  'xique xique': 'xiquexique',
  'muquem de sao francisco': 'muquem do sao francisco'
};

/**
 * Verifica se um município faz parte do Semiárido Baiano
 * @param {string} nomeMunicipio
 * @returns {boolean}
 */
export function isMunicipioSemiarido(nomeMunicipio) {
  if (!nomeMunicipio) return false;
  let norm = normalizeMunicipioName(nomeMunicipio);
  norm = CORRECOES_SEMIARIDO[norm] || norm;
  return SEMIARIDO_MUNICIPIOS_NORMALIZADOS.has(norm);
}
